// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (room_id, user_id, content)
VALUES ($1, $2, $3)
`

type CreateMessageParams struct {
	RoomID  int64  `json:"room_id"`
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage, arg.RoomID, arg.UserID, arg.Content)
	return err
}
