// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	CreateRoomAddMember(ctx context.Context, arg CreateRoomAddMemberParams) error
	GetRoomByID(ctx context.Context, id int64) (Room, error)
}

var _ Querier = (*Queries)(nil)
