// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomAddMember(ctx context.Context, arg CreateRoomAddMemberParams) error
	GetListRoom(ctx context.Context) ([]Room, error)
	GetRoomByID(ctx context.Context, id int64) (Room, error)
	GetRoomMemberByUsername(ctx context.Context, arg GetRoomMemberByUsernameParams) (RoomMember, error)
	JoinRoomByUsername(ctx context.Context, arg JoinRoomByUsernameParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
