// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_members.sql

package sqlc

import (
	"context"
)

const createRoomAddMember = `-- name: CreateRoomAddMember :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
`

type CreateRoomAddMemberParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CreateRoomAddMember(ctx context.Context, arg CreateRoomAddMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomAddMember, arg.RoomID, arg.UserID)
	return err
}

const getRoomMemberByUsername = `-- name: GetRoomMemberByUsername :one
SELECT  room_members.room_id,
        room_members.user_id,
        room_members.joined_at
FROM    room_members
JOIN    users ON users.id = room_members.user_id
WHERE   room_members.room_id = $1
AND     users.username = $2
`

type GetRoomMemberByUsernameParams struct {
	RoomID   int64  `json:"room_id"`
	Username string `json:"username"`
}

func (q *Queries) GetRoomMemberByUsername(ctx context.Context, arg GetRoomMemberByUsernameParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, getRoomMemberByUsername, arg.RoomID, arg.Username)
	var i RoomMember
	err := row.Scan(&i.RoomID, &i.UserID, &i.JoinedAt)
	return i, err
}

const joinRoomByUsername = `-- name: JoinRoomByUsername :execrows
INSERT INTO room_members (room_id, user_id)
SELECT  $1, id
FROM    users
WHERE   username = $2
ON CONFLICT (room_id, user_id) DO NOTHING
`

type JoinRoomByUsernameParams struct {
	RoomID   int64  `json:"room_id"`
	Username string `json:"username"`
}

func (q *Queries) JoinRoomByUsername(ctx context.Context, arg JoinRoomByUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, joinRoomByUsername, arg.RoomID, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
