// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_members.sql

package sqlc

import (
	"context"
)

const createRoomAddMember = `-- name: CreateRoomAddMember :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
`

type CreateRoomAddMemberParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CreateRoomAddMember(ctx context.Context, arg CreateRoomAddMemberParams) error {
	_, err := q.db.Exec(ctx, createRoomAddMember, arg.RoomID, arg.UserID)
	return err
}
